const segment = {
  basic: 'Basic',
  medium: 'Medium',
  advanced: 'Advanced',
};

const quiz = {
  quizTitle: 'Sachunterricht Österreich Quiz',
  quizSynopsis: 'Quiz zu Österreich: Bundesländer, Geografie, Politik und Besonderheiten.',
  nrOfQuestions: '25',
  progressBarColor: '#9de1f6',
  questions: [
    {
      question: 'Was ist die Hauptstadt von Vorarlberg?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Bregenz', 'Innsbruck', 'Linz', 'Graz'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Richtig! Bregenz ist die Hauptstadt von Vorarlberg.',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Vorarlberg hat seine Landeshauptstadt in Bregenz.',
      point: '10',
      segment: segment.basic,
    },
    {
      question: 'Was ist die Hauptstadt von Tirol?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Salzburg', 'Innsbruck', 'Klagenfurt', 'Eisenstadt'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Innsbruck ist die Landeshauptstadt von Tirol.',
      point: '10',
      segment: segment.basic,
    },
    {
      question: 'Was ist die Hauptstadt der Steiermark?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Graz', 'Linz', 'St. Pölten', 'Wien'],
      correctAnswer: '1',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Graz ist die Hauptstadt der Steiermark.',
      point: '10',
      segment: segment.basic,
    },
    {
      question: 'Welche Länder grenzen an Österreich? (Mehrfachauswahl)',
      questionType: 'text',
      answerSelectionType: 'multiple',
      answers: [
        'Deutschland',
        'Frankreich',
        'Italien',
        'Ungarn',
        'Spanien',
        'Schweiz'
      ],
      correctAnswer: [1, 3, 4, 6],
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Österreich grenzt u.a. an Deutschland, Italien, Ungarn und die Schweiz.',
      point: '20',
      segment: segment.medium,
    },
    {
      question: 'Wie viele Einwohner hat Österreich ungefähr?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['5 Millionen', '7 Millionen', '9 Millionen', '12 Millionen'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Österreich hat etwa 9 Millionen Einwohner.',
      point: '10',
      segment: segment.basic,
    },
    {
      question: 'Welche Regierungsform hat Österreich?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Monarchie',
        'Demokratische Republik',
        'Diktatur',
        'Kaiserreich'
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Österreich ist eine demokratische Republik.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Was ist die Amtssprache in Österreich?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Englisch', 'Deutsch', 'Ungarisch', 'Französisch'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Die Amtssprache in Österreich ist Deutsch.',
      point: '10',
      segment: segment.basic,
    },
    {
      question: 'Wie heißt der längste Fluss in Österreich?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Inn', 'Mur', 'Donau', 'Drau'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Die Donau ist der längste Fluss Österreichs.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Wie heißt der höchste Berg Österreichs?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Zugspitze', 'Großglockner', 'Piz Buin', 'Dachstein'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Der Großglockner ist der höchste Berg Österreichs.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Seit wann ist Österreich Mitglied der EU?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1989', '1995', '2001', '2004'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Österreich ist seit 1995 Mitglied der EU.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Wie groß ist der Anteil der Alpen in Österreich?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['30%', '45%', '62%', '80%'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: '62% Österreichs bestehen aus Alpen.',
      point: '20',
      segment: segment.advanced,
    },
    {
      question: 'In welches Meer fließt die Donau?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['Mittelmeer', 'Nordsee', 'Schwarzes Meer', 'Ostsee'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Die Donau mündet ins Schwarze Meer.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Wie viele Bezirke hat Wien?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['9', '16', '23', '25'],
      correctAnswer: '3',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Wien hat 23 Bezirke.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Wie heißt der aktuelle Bundespräsident Österreichs?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: [
        'Karl Nehammer',
        'Alexander van der Bellen',
        'Sebastian Kurz',
        'Werner Kogler'
      ],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Der Bundespräsident heißt Alexander van der Bellen.',
      point: '15',
      segment: segment.medium,
    },
    {
      question: 'Wann ist der österreichische Nationalfeiertag?',
      questionType: 'text',
      answerSelectionType: 'single',
      answers: ['1. Mai', '26. Oktober', '12. Februar', '15. August'],
      correctAnswer: '2',
      messageForCorrectAnswer: 'Richtig!',
      messageForIncorrectAnswer: 'Leider falsch.',
      explanation: 'Der Nationalfeiertag ist am 26. Oktober.',
      point: '10',
      segment: segment.basic,
    }
  ],
};

export default quiz;
